"""init schema (cities, world_state)

Revision ID: 70c70888b30a
Revises: 3e21767ad59d
Create Date: 2025-11-09 18:13:19.076819

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '70c70888b30a'
down_revision: Union[str, Sequence[str], None] = '3e21767ad59d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
