"""add action_commands table for S2-03

Revision ID: 73d3f5e150bd
Revises: 41debadee1fc
Create Date: 2025-11-14 21:39:46.019220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73d3f5e150bd'
down_revision: Union[str, Sequence[str], None] = '41debadee1fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('intent', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('valid_from_tick', sa.Integer(), nullable=False),
    sa.Column('expires_at_tick', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSED', 'REJECTED', 'EXPIRED', name='actioncommandstatus', native_enum=False, length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at_tick', sa.Integer(), nullable=True),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'intent', 'valid_from_tick', name='uq_player_intent_tick')
    )
    op.create_index(op.f('ix_action_commands_expires_at_tick'), 'action_commands', ['expires_at_tick'], unique=False)
    op.create_index(op.f('ix_action_commands_id'), 'action_commands', ['id'], unique=False)
    op.create_index(op.f('ix_action_commands_player_id'), 'action_commands', ['player_id'], unique=False)
    op.create_index('ix_action_commands_queue_processing', 'action_commands', ['status', 'valid_from_tick', 'expires_at_tick'], unique=False)
    op.create_index(op.f('ix_action_commands_status'), 'action_commands', ['status'], unique=False)
    op.create_index(op.f('ix_action_commands_valid_from_tick'), 'action_commands', ['valid_from_tick'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_commands_valid_from_tick'), table_name='action_commands')
    op.drop_index(op.f('ix_action_commands_status'), table_name='action_commands')
    op.drop_index('ix_action_commands_queue_processing', table_name='action_commands')
    op.drop_index(op.f('ix_action_commands_player_id'), table_name='action_commands')
    op.drop_index(op.f('ix_action_commands_id'), table_name='action_commands')
    op.drop_index(op.f('ix_action_commands_expires_at_tick'), table_name='action_commands')
    op.drop_table('action_commands')
    # ### end Alembic commands ###
