"""add event sourcing tables for S2-04

Revision ID: aa1713489de7
Revises: 73d3f5e150bd
Create Date: 2025-11-14 22:50:08.629463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa1713489de7'
down_revision: Union[str, Sequence[str], None] = '73d3f5e150bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('prosperity', sa.Integer(), nullable=False),
    sa.Column('unrest', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('snapshot_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tick', 'city_id', name='uq_city_snapshot_tick')
    )
    op.create_index(op.f('ix_city_snapshots_city_id'), 'city_snapshots', ['city_id'], unique=False)
    op.create_index('ix_city_snapshots_city_tick', 'city_snapshots', ['city_id', 'tick'], unique=False)
    op.create_index(op.f('ix_city_snapshots_id'), 'city_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_city_snapshots_tick'), 'city_snapshots', ['tick'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('command_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_actor'), 'events', ['actor'], unique=False)
    op.create_index(op.f('ix_events_command_id'), 'events', ['command_id'], unique=False)
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_tick'), 'events', ['tick'], unique=False)
    op.create_index('ix_events_tick_created', 'events', ['tick', 'created_at'], unique=False)
    op.create_index('ix_events_type_tick', 'events', ['event_type', 'tick'], unique=False)
    op.create_table('world_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.Column('current_tick', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('snapshot_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_world_snapshots_id'), 'world_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_world_snapshots_tick'), 'world_snapshots', ['tick'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_world_snapshots_tick'), table_name='world_snapshots')
    op.drop_index(op.f('ix_world_snapshots_id'), table_name='world_snapshots')
    op.drop_table('world_snapshots')
    op.drop_index('ix_events_type_tick', table_name='events')
    op.drop_index('ix_events_tick_created', table_name='events')
    op.drop_index(op.f('ix_events_tick'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_index(op.f('ix_events_command_id'), table_name='events')
    op.drop_index(op.f('ix_events_actor'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_city_snapshots_tick'), table_name='city_snapshots')
    op.drop_index(op.f('ix_city_snapshots_id'), table_name='city_snapshots')
    op.drop_index('ix_city_snapshots_city_tick', table_name='city_snapshots')
    op.drop_index(op.f('ix_city_snapshots_city_id'), table_name='city_snapshots')
    op.drop_table('city_snapshots')
    # ### end Alembic commands ###
